import express from "express";
import Arvore_ImagensRoutes from "./Arvore_ImagensRoutes";
import ArvoreRoutes from "./ArvoreRoutes";
import ClasseRoutes from "./ClasseRoutes";
import EspecieRoutes from "./EspecieRoutes";
import FamiliaRoutes from "./FamiliaRoutes";
import GeneroRoutes from "./GeneroRoutes";
import OrdemRoutes from "./OrdemRoutes";
import UsuarioRoutes from "./UsuarioRoutes";
import LocalizacaoRoutes from "./LocalizacaoRoutes";
import FiloRoutes from "./FiloRoutes";
import SistemaRoutes from "./SistemaRoutes";
import GrupoRoutes from "./GrupoRoutes";
import ReinoRoutes from "./ReinoRoutes";
import TipoRoutes from "./TipoRoutes";
import DataRoutes from "./DataRoutes";

const router = express.Router();

router.post('/arvores_imagens', Arvore_ImagensRoutes);
router.post('/arvores', ArvoreRoutes);
router.post('/classes', ClasseRoutes);
router.post('/especies', EspecieRoutes);
router.post('/familias', FamiliaRoutes);
router.post('/generos', GeneroRoutes);
router.post('/ordens', OrdemRoutes);
router.post('/usuarios', UsuarioRoutes);
router.post('/localizacoes', LocalizacaoRoutes);
router.post('/filos', FiloRoutes);
router.post('/sistemas', SistemaRoutes);
router.post('/grupos', GrupoRoutes);
router.post('/reinos', ReinoRoutes);
router.post('/tipos', TipoRoutes);
router.post('/datas', DataRoutes);

router.patch('/arvores_imagens/:id', Arvore_ImagensRoutes);
router.patch('/arvores/:id', ArvoreRoutes);
router.patch('/classes/:id', ClasseRoutes);
router.patch('/especies/:id', EspecieRoutes);
router.patch('/familias/:id', FamiliaRoutes);
router.patch('/generos/:id', GeneroRoutes);
router.patch('/ordens/:id', OrdemRoutes);
router.patch('/usuarios/:id', UsuarioRoutes);
router.patch('/localizacoes/:id', LocalizacaoRoutes);
router.patch('/filos/:id', FiloRoutes);
router.patch('/sistemas/:id', SistemaRoutes);
router.patch('/grupos/:id', GrupoRoutes);
router.patch('/reinos/:id', ReinoRoutes);
router.patch('/tipos/:id', TipoRoutes);
router.patch('/datas/:id', DataRoutes);

router.delete('/arvores_imagens/:id', Arvore_ImagensRoutes);
router.delete('/arvores/:id', ArvoreRoutes);
router.delete('/classes/:id', ClasseRoutes);
router.delete('/especies/:id', EspecieRoutes);
router.delete('/familias/:id', FamiliaRoutes);
router.delete('/generos/:id', GeneroRoutes);
router.delete('/ordens/:id', OrdemRoutes);
router.delete('/usuarios/:id', UsuarioRoutes);
router.delete('/localizacoes/:id', LocalizacaoRoutes);
router.delete('/filos/:id', FiloRoutes);
router.delete('/sistemas/:id', SistemaRoutes);
router.delete('/grupos/:id', GrupoRoutes);
router.delete('/reinos/:id', ReinoRoutes);
router.delete('/tipos/:id', TipoRoutes);
router.delete('/datas/:id', DataRoutes);

router.get('/arvores_imagens', Arvore_ImagensRoutes);
router.get('/arvores', ArvoreRoutes);
router.get('/classes', ClasseRoutes);
router.get('/especies', EspecieRoutes);
router.get('/familias', FamiliaRoutes);
router.get('/generos', GeneroRoutes);
router.get('/ordens', OrdemRoutes);
router.get('/usuarios', UsuarioRoutes);
router.get('/localizacoes', LocalizacaoRoutes);
router.get('/filos', FiloRoutes);
router.get('/sistemas', SistemaRoutes);
router.get('/grupos', GrupoRoutes);
router.get('/reinos', ReinoRoutes);
router.get('/tipos', TipoRoutes);
router.get('/datas', DataRoutes);

router.get('/arvores_imagens/:id', Arvore_ImagensRoutes);
router.get('/arvores/:id', ArvoreRoutes);
router.get('/classes/:id', ClasseRoutes);
router.get('/especies/:id', EspecieRoutes);
router.get('/familias/:id', FamiliaRoutes);
router.get('/generos/:id', GeneroRoutes);
router.get('/ordens/:id', OrdemRoutes);
router.get('/usuarios/:id', UsuarioRoutes);
router.get('/localizacoes/:id', LocalizacaoRoutes);
router.get('/filos/:id', FiloRoutes);
router.get('/sistemas/:id', SistemaRoutes);
router.get('/grupos/:id', GrupoRoutes);
router.get('/reinos/:id', ReinoRoutes);
router.get('/tipos/:id', TipoRoutes);
router.get('/datas/:id', DataRoutes);

export default router;